/* HADO app 3.0.0.0 Update05 core */
(()=>{'use strict';
const EV={add:'hado:formation-candidate-tray-add',request:'hado:formation-candidate-tray-snapshot-request',snapshot:'hado:formation-candidate-tray-snapshot',remove:'hado:formation-candidate-tray-remove',clear:'hado:formation-candidate-tray-clear',place:'hado:formation-candidate-tray-place'};
const TYPE_KEY='hado.typeEntry.selection.v1';
const normText=v=>String(v??'').normalize('NFKC').trim();
const escapeHtml=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const formation=()=>getCurrentFormation();
const sanitize=v=>sanitizeFormationCandidateTray(v||[]);
function publish(){const f=formation();dispatchEvent(new CustomEvent(EV.snapshot,{detail:{formationId:f?.id||'',formationName:f?.name||'',evaluationTypeId:f?.evaluationTypeId||'',items:sanitize(f?.candidateTray)}}))}
function persist(context){const f=formation();if(f){f.updatedAt=new Date().toISOString();state.formationDirty=true}saveFormationDataToStorage(context);publish()}
function selectedType(){try{return JSON.parse(localStorage.getItem(TYPE_KEY)||'{}')}catch{return{}}}
function trayId(v){return ['tray',v.roleId,v.typeId,v.name].map(normText).join('_').replace(/[^\w\u3000-\u9fff\u3040-\u30ff-]/g,'_')}
function add(detail){const f=ensureCurrentFormation(),selected=selectedType();const row={roleId:normText(detail.roleId),name:normalizeSaveItemName(detail.name),typeId:normText(detail.typeId||selected.typeId),typeName:normText(detail.typeName||selected.typeName||selected.typeId),source:'型候補一覧',addedAt:new Date().toISOString()};row.id=trayId(row);if(!row.roleId||!row.name)return;f.evaluationTypeId=row.typeId||f.evaluationTypeId;f.candidateTray=sanitize(f.candidateTray);if(!f.candidateTray.some(v=>v.id===row.id))f.candidateTray.push(row);persist('candidateTray:add')}
function remove(id){const f=formation();if(!f)return;f.candidateTray=sanitize(f.candidateTray).filter(v=>v.id!==normText(id));persist('candidateTray:remove')}
function clear(){const f=formation();if(!f)return;f.candidateTray=[];persist('candidateTray:clear')}
function destinations(row){const f=formation(),out=[],push=(label,type,slotKey,equipKey='')=>out.push({label,type,slotKey,equipKey});if(row.roleId==='main_general')push('主将','general','main');if(row.roleId==='vice_general'){push('副将1','general','deputy1');push('副将2','general','deputy2')}if(row.roleId==='support_general'){push('補佐1','general','support1');push('補佐2','general','support2')}if(row.roleId==='attendant')FORMATION_SLOT_SPECS.forEach(s=>{if(f.slots?.[s.key]?.general)push(`${s.label}の侍従`,'attendant',s.key)});if(row.roleId==='equipment')FORMATION_SLOT_SPECS.forEach(s=>{if(f.slots?.[s.key]?.general)EQUIP_SLOT_SPECS.forEach(e=>push(`${s.label} → ${e.label}`,'equipment',s.key,e.key))});return out}
function handoff(row,dest){document.getElementById('hctp')?.remove();setMainTab('formation');state.formationSelectedSlot=dest.slotKey;openFormationSelectorDialog(dest.type,dest.slotKey,dest.equipKey,'');if(state.formationSelectorDialog)state.formationSelectorDialog.keyword=row.name;renderFormationScreen()}
function place(id){const row=sanitize(formation()?.candidateTray).find(v=>v.id===normText(id));if(!row)return;const list=destinations(row);if(!list.length)return alert('配置先候補がありません。必要な部隊枠を先に設定してください。');const overlay=document.createElement('div');overlay.id='hctp';overlay.style='position:fixed;inset:0;z-index:99995;background:#0f172a94;display:flex;align-items:center;justify-content:center;padding:16px';overlay.innerHTML=`<section style="width:min(620px,100%);background:#fff;border-radius:16px;padding:16px"><h2>配置先を選択</h2><p>${escapeHtml(row.name)} は既存ダイアログで条件判定後に登録します。</p>${list.map((v,i)=>`<button data-d="${i}">${escapeHtml(v.label)}</button>`).join(' ')} <button data-x>閉じる</button></section>`;document.body.appendChild(overlay);overlay.querySelector('[data-x]').onclick=()=>overlay.remove();overlay.querySelectorAll('[data-d]').forEach(b=>b.onclick=()=>handoff(row,list[Number(b.dataset.d)]))}
function patchCandidateCards(){document.querySelectorAll('#htc-modal .htc-item').forEach(card=>{if(card.querySelector('[data-tray-add]'))return;const name=normText(card.querySelector('.htc-title')?.textContent);if(!name)return;const button=document.createElement('button');button.type='button';button.dataset.trayAdd='1';button.className='htc-btn';button.textContent='候補トレイへ追加';button.onclick=e=>{e.preventDefault();e.stopPropagation();add({roleId:document.querySelector('#htc-modal .htc-tab.on')?.dataset.role||'',name})};card.appendChild(button)})}
addEventListener(EV.add,e=>add(e.detail||{}));addEventListener(EV.request,publish);addEventListener(EV.remove,e=>remove(e.detail?.id));addEventListener(EV.clear,clear);addEventListener(EV.place,e=>place(e.detail?.id));new MutationObserver(patchCandidateCards).observe(document.documentElement,{childList:true,subtree:true});patchCandidateCards();publish();
})();
