/* HADO app 3.0.0.0 Update06: candidate list with canonical identity handoff */
(()=>{'use strict';
const KEY='hado.typeEntry.selection.v1',EV='hado:type-search-entry-selected',FILES=['hadou_type_search_role_index.json','hadou_type_score_rules.json','hadou_type_purpose_rules.json'];
const ROLES=[['main_general','主将'],['vice_general','副将'],['support_general','補佐'],['attendant','侍従'],['equipment','装備'],['formation','陣形'],['siege_weapon','兵器'],['warhorse','名馬'],['warhorse_skill','軍馬技能']];
const ALIAS={troops:['兵力'],tactic_power:['戦法威力'],critical_tactic_power:['撃心威力'],critical_power:['会心威力'],attack_speed:['攻撃速度'],critical_rate:['会心発生','会心発生率'],critical_tactic_rate:['撃心発生','撃心発生率'],normal_attack_power:['通常攻撃威力'],normal_attack_target_count:['通常攻撃対象数','通常攻撃対象部隊数'],range:['射程'],anti_object:['対物特効'],tactic_speed:['戦法速度'],weakening_nullify:['弱化無効','弱化効果無効'],weakening_remove:['弱化解除','弱化効果解除'],strengthening_remove_avoid:['強化解除回避'],strengthening_seize_avoid:['強化奪取回避'],annihilation_avoidance:['壊滅回避'],remaining_troops:['残存兵力'],wounded_recovery:['負傷兵回復','兵力回復'],damage_reduction:['被ダメージ軽減'],tactic_reduction:['戦法短縮'],initial_tactic_gauge:['出陣時戦法ゲージ'],chain_rate:['連鎖率','連鎖確率'],status_effect_rate:['状態変化発生率'],tactic_delay:['戦法遅延'],chain_nullify:['連鎖無効'],enemy_attack_debuff:['敵部隊攻撃低下'],enemy_defense_debuff:['敵部隊防御低下'],ally_buff_multi:['味方バフ配布','有利変化','強化効果'],ally_target_count:['味方対象部隊数','味方部隊'],effect_duration:['効果時間','秒間'],enemy_debuff_multi:['敵デバフ配布','不利変化','弱化効果'],enemy_target_count:['敵対象部隊数','敵部隊'],enemy_anti_object_debuff:['敵部隊対物特効低下','対物特効低下'],ally_wounded_recovery:['味方負傷兵回復','味方部隊の負傷兵'],ally_defense_buff:['味方防御上昇','味方部隊の防御'],combat_start_tactic_gauge:['交戦開始時戦法ゲージ'],self_disadvantage_countermeasure:['自部隊不利対策','skill_effect:self_disadvantage_countermeasure'],ally_non_damage_effect:['味方非ダメージ効果','skill_effect:ally_non_damage_effect']};
const st={data:null,role:'main_general',q:'',sel:null};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])), norm=s=>String(s??'').normalize('NFKC').replace(/\s+/g,'').toLowerCase(), flat=v=>Array.isArray(v)?v.map(flat).join(' '):(v&&typeof v==='object'?Object.values(v).map(flat).join(' '):String(v??'')), items=(v,ks)=>{if(Array.isArray(v))return v;for(const k of ks)if(Array.isArray(v?.[k]))return v[k];return[]};
const loadSel=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'null')}catch{return null}}, fetchJson=async f=>{const r=await fetch(f,{cache:'no-store'});if(!r.ok)throw Error(`${f}: HTTP ${r.status}`);return r.json()};
const type=()=>st.data?.types.find(v=>v.typeId===st.sel?.typeId), purpose=()=>st.data?.purposes.find(v=>v.purposeId===st.sel?.purposeId);
function score(x){const t=norm(flat([x.typeFeatures||[],x.statusEffectRefs||[]])),ms=(type()?.metrics||[]).slice(0,5),matched=ms.filter(m=>[m.label,...(ALIAS[m.metricKey]||[])].some(a=>a&&t.includes(norm(a))));return{matched,total:ms.length||5}}
function roleRows(role){const q=norm(st.q);return st.data.roles.filter(v=>v.roleId===role).map(v=>({...v,_s:score(v)})).filter(v=>v._s.matched.length>0).filter(v=>!q||norm(flat([v.displayName,v.name,v.typeFeatures,v.statusEffectRefs])).includes(q)).sort((a,b)=>b._s.matched.length-a._s.matched.length||Number(a.sourceIndex||0)-Number(b.sourceIndex||0))}
function rows(){return roleRows(st.role)}
function chipLabel(x){if(x==null)return '';if(typeof x==='string'||typeof x==='number')return String(x);if(Array.isArray(x))return x.map(chipLabel).filter(Boolean).join(' / ');if(typeof x==='object')return String(x.label||x.statusEffectName||x.displayName||x.name||x.featureId||'');return ''}
function chipLabels(v){return [...new Set([...(v.typeFeatures||[]),...(v.statusEffectRefs||[])].map(chipLabel).filter(Boolean))]}
function canonicalName(v){return String(v?.name||v?.displayName||'').trim()}
function displayName(v){return String(v?.displayName||v?.name||'').trim()}
function style(){if(document.getElementById('htc-style'))return;const e=document.createElement('style');e.id='htc-style';e.textContent=`#htc-open{position:fixed;right:18px;bottom:72px;z-index:99990;border:1px solid #1d4ed8;border-radius:999px;padding:11px 17px;background:#fff;color:#1d4ed8;font-weight:700;cursor:pointer}#htc-open:disabled{opacity:.5}#htc-overlay{position:fixed;inset:0;z-index:99992;background:#0f172a94;display:flex;align-items:center;justify-content:center;padding:16px}#htc-modal{width:min(1040px,100%);max-height:92dvh;background:#fff;border-radius:18px;display:grid;grid-template-rows:auto auto auto minmax(0,1fr) auto;overflow:hidden;color:#172033}.htc-p{padding:14px 18px}.htc-head,.htc-foot{display:flex;justify-content:space-between;gap:10px}.htc-tabs{display:flex;gap:7px;flex-wrap:wrap;background:#f8fafc}.htc-btn,.htc-tab{border:1px solid #cbd5e1;background:#fff;border-radius:10px;padding:8px 11px;cursor:pointer}.htc-tab.on{border-color:#2563eb;background:#eff6ff;color:#1d4ed8;font-weight:700}.htc-search{width:100%;padding:10px;border:1px solid #cbd5e1;border-radius:10px}.htc-body{overflow:auto}.htc-list{display:grid;gap:8px}.htc-item{border:1px solid #d8e0eb;border-radius:12px;padding:11px}.htc-title{font-weight:700}.htc-note,.htc-detail,.htc-score{font-size:12px;color:#64748b;line-height:1.55;margin-top:4px}.htc-score{font-weight:700;color:#334155}.htc-chip{display:inline-block;border-radius:999px;padding:2px 7px;background:#eef2ff;color:#3730a3;margin:2px 4px 0 0}@media(max-width:720px){#htc-overlay{padding:0}#htc-modal{width:100%;height:100dvh;max-height:none;border-radius:0}}`;document.head.appendChild(e)}
function close(){document.getElementById('htc-overlay')?.remove()}
function render(){const m=document.getElementById('htc-modal'),rs=rows();m.innerHTML=`<div class="htc-p htc-head"><div><h2>型候補一覧</h2><div class="htc-note">3.0.0.0 Update06 / 選択中の型: ${esc(type()?.typeName||'未選択')} / 目的: ${esc(purpose()?.purposeName||'指定なし')}</div></div><button class="htc-btn" data-close>閉じる</button></div><div class="htc-p htc-tabs">${ROLES.map(([id,l])=>`<button class="htc-tab ${st.role===id?'on':''}" data-role="${id}">${l} (${roleRows(id).length})</button>`).join('')}</div><div class="htc-p"><input id="htc-q" class="htc-search" placeholder="名称・特徴で絞り込み" value="${esc(st.q)}"><div class="htc-note">同一型内の参考一致数で候補を並べます。参考一致数が0件の候補は表示しません。異なる型同士の順位付けには使いません。配置や成立判定は行いません。侍従・陣形・兵科・射程・装備重複などの既存ゲートは、部隊編成へ登録する次段階で必ず通します。</div></div><div class="htc-p htc-body"><div class="htc-list">${rs.map(v=>`<div class="htc-item" data-role-id="${esc(v.roleId||st.role)}" data-canonical-name="${esc(canonicalName(v))}" data-display-name="${esc(displayName(v))}"><div class="htc-title">${esc(displayName(v))}</div><div class="htc-score">参考一致数: ${v._s.matched.length}/${v._s.total}項目${v._s.matched.length?' / '+v._s.matched.map(m=>esc(m.label)).join('、'):''}</div><div class="htc-detail">${chipLabels(v).map(x=>`<span class="htc-chip">${esc(x)}</span>`).join('')}</div></div>`).join('')||'<div class="htc-note">該当候補がありません。</div>'}</div></div><div class="htc-p htc-foot"><div class="htc-note">候補表示のみです。自動配置・保存データ変更は行いません。</div><button class="htc-btn" data-close>閉じる</button></div>`;m.querySelectorAll('[data-close]').forEach(b=>b.onclick=close);m.querySelectorAll('[data-role]').forEach(b=>b.onclick=()=>{st.role=b.dataset.role;st.q='';render()});m.querySelector('#htc-q').oninput=e=>{st.q=e.target.value;render()}}
async function open(){st.sel=loadSel();if(!st.sel?.typeId)return alert('型編成ナビで型を選択し、「選択を保存」を押してください。');if(!st.data){const[a,b,c]=await Promise.all(FILES.map(fetchJson));st.data={roles:items(a,['items']),types:items(b,['items','types']),purposes:items(c,['items','purposes'])}}if(!type())throw Error(`選択中の型が見つかりません: ${st.sel.typeId}`);close();const o=document.createElement('div');o.id='htc-overlay';o.innerHTML='<section id="htc-modal"></section>';o.onclick=e=>{if(e.target===o)close()};document.body.appendChild(o);render()}
function isFormationTab(){return typeof window.state==='object'?window.state.mainTab==='formation':document.getElementById('formationScreen')&&!document.getElementById('formationScreen').classList.contains('tab-content-hidden')}
function syncVisibility(){const b=document.getElementById('htc-open');const visible=!!isFormationTab();if(b)b.hidden=!visible;if(!visible)close()}
function refresh(){const b=document.getElementById('htc-open');if(b)b.disabled=!loadSel()?.typeId;syncVisibility()}
function mount(){style();const b=document.createElement('button');b.id='htc-open';b.textContent='型候補一覧';b.onclick=()=>open().catch(e=>alert(`型候補一覧の読込に失敗しました。\n${e.message}`));document.body.appendChild(b);refresh();addEventListener(EV,refresh);addEventListener('storage',refresh);new MutationObserver(syncVisibility).observe(document.documentElement,{attributes:true,subtree:true,attributeFilter:['class']});setInterval(syncVisibility,400)}
if(document.readyState==='loading')addEventListener('DOMContentLoaded',mount);else mount();
})();
