/* HADO app 3.0.0.0 candidate tray UI and existing-gate handoff */
(()=>{'use strict';
const REQUEST='hado:formation-candidate-tray-snapshot-request';
const SNAPSHOT='hado:formation-candidate-tray-snapshot';
const REMOVE='hado:formation-candidate-tray-remove';
const CLEAR='hado:formation-candidate-tray-clear';
const PLACE='hado:formation-candidate-tray-place';
const ROLE_LABELS={main_general:'主将',vice_general:'副将',support_general:'補佐',attendant:'侍従',equipment:'装備',formation:'陣形',siege_weapon:'兵器',warhorse:'名馬',warhorse_skill:'軍馬技能'};
const DIRECT_HANDOFF_ROLES=new Set(Object.keys(ROLE_LABELS));
let snapshot={formationId:'',formationName:'',evaluationTypeId:'',items:[]};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function requestSnapshot(context='ui'){dispatchEvent(new CustomEvent(REQUEST,{detail:{context}}));}
function style(){if(document.getElementById('hct-style'))return;const e=document.createElement('style');e.id='hct-style';e.textContent=`#hct-open{position:fixed;right:18px;bottom:126px;z-index:99990;border:1px solid #0f766e;border-radius:999px;padding:11px 17px;background:#fff;color:#0f766e;font-weight:700;cursor:pointer;box-shadow:0 6px 18px rgba(15,118,110,.16)}#hct-count{display:inline-flex;align-items:center;justify-content:center;min-width:22px;height:22px;margin-left:6px;border-radius:999px;background:#0f766e;color:#fff;font-size:12px}#hct-overlay{position:fixed;inset:0;z-index:99993;background:#0f172a94;display:flex;align-items:center;justify-content:center;padding:16px}#hct-modal{width:min(920px,100%);max-height:92dvh;background:#fff;border-radius:18px;display:grid;grid-template-rows:auto auto minmax(0,1fr) auto;overflow:hidden;color:#172033}.hct-p{padding:14px 18px}.hct-head,.hct-foot{display:flex;justify-content:space-between;gap:10px;align-items:center}.hct-head{border-bottom:1px solid #d9e1ec}.hct-body{overflow:auto}.hct-note,.hct-meta{font-size:12px;color:#64748b;line-height:1.6}.hct-list{display:grid;gap:8px}.hct-item{border:1px solid #d8e0eb;border-radius:12px;padding:11px;display:grid;gap:7px}.hct-title{font-weight:700}.hct-actions{display:flex;gap:7px;flex-wrap:wrap}.hct-btn{border:1px solid #cbd5e1;background:#fff;border-radius:9px;padding:8px 11px;cursor:pointer}.hct-btn.primary{border-color:#0f766e;background:#f0fdfa;color:#0f766e;font-weight:700}.hct-btn.danger{border-color:#fca5a5;background:#fff7f7;color:#b91c1c}.hct-badge{display:inline-block;border-radius:999px;padding:2px 8px;background:#ecfeff;color:#155e75;font-size:11px;margin-right:6px}.hct-empty{padding:24px;border:1px dashed #cbd5e1;border-radius:12px;color:#64748b;text-align:center}@media(max-width:720px){#hct-overlay{padding:0}#hct-modal{width:100%;height:100dvh;max-height:none;border-radius:0}.hct-p{padding:12px}}`;document.head.appendChild(e)}
function close(){document.getElementById('hct-overlay')?.remove()}
function itemHtml(row){const role=ROLE_LABELS[row.roleId]||row.roleId||'候補';const supported=DIRECT_HANDOFF_ROLES.has(row.roleId);return `<div class="hct-item"><div><span class="hct-badge">${esc(role)}</span><span class="hct-title">${esc(row.displayName||row.name||'名称未設定')}</span></div><div class="hct-meta">型: ${esc(row.typeName||row.typeId||'未指定')} / 追加元: ${esc(row.source||'型候補一覧')}</div><div class="hct-actions">${supported?`<button type="button" class="hct-btn primary" data-hct-place="${esc(row.id)}">配置先を選ぶ</button>`:`<span class="hct-note">候補保存のみです。</span>`}<button type="button" class="hct-btn danger" data-hct-remove="${esc(row.id)}">トレイから削除</button></div></div>`}
function render(){const m=document.getElementById('hct-modal');if(!m)return;const rows=Array.isArray(snapshot.items)?snapshot.items:[];m.innerHTML=`<div class="hct-p hct-head"><div><h2>候補トレイ</h2><div class="hct-note">3.0.0.0 Update06 / 部隊: ${esc(snapshot.formationName||'未選択')} / 評価型: ${esc(snapshot.evaluationTypeId||'未指定')}</div></div><button type="button" class="hct-btn" data-hct-close>閉じる</button></div><div class="hct-p hct-note">型候補一覧で気になった候補を部隊単位で保持します。「配置先を選ぶ」は既存の部隊編成処理へ委譲し、成立判定を迂回しません。</div><div class="hct-p hct-body"><div class="hct-list">${rows.length?rows.map(itemHtml).join(''):'<div class="hct-empty">候補トレイは空です。型候補一覧から追加してください。</div>'}</div></div><div class="hct-p hct-foot"><div class="hct-note">候補数: ${rows.length}件</div><div class="hct-actions">${rows.length?'<button type="button" class="hct-btn danger" data-hct-clear>すべて削除</button>':''}<button type="button" class="hct-btn" data-hct-close>閉じる</button></div></div>`;m.querySelectorAll('[data-hct-close]').forEach(b=>b.onclick=close);m.querySelectorAll('[data-hct-remove]').forEach(b=>b.onclick=()=>dispatchEvent(new CustomEvent(REMOVE,{detail:{id:b.dataset.hctRemove}})));m.querySelectorAll('[data-hct-place]').forEach(b=>b.onclick=()=>{dispatchEvent(new CustomEvent(PLACE,{detail:{id:b.dataset.hctPlace}}));close()});m.querySelectorAll('[data-hct-clear]').forEach(b=>b.onclick=()=>dispatchEvent(new CustomEvent(CLEAR)))}
function open(){style();close();const o=document.createElement('div');o.id='hct-overlay';o.innerHTML='<section id="hct-modal" role="dialog" aria-modal="true" aria-label="候補トレイ"></section>';o.onclick=e=>{if(e.target===o)close()};document.body.appendChild(o);requestSnapshot('open');render()}
function refreshButton(){const n=Array.isArray(snapshot.items)?snapshot.items.length:0;const c=document.getElementById('hct-count');if(c)c.textContent=String(n)}
function isFormationTab(){return typeof window.state==='object'?window.state.mainTab==='formation':document.getElementById('formationScreen')&&!document.getElementById('formationScreen').classList.contains('tab-content-hidden')}
function syncVisibility(){const b=document.getElementById('hct-open');const visible=!!isFormationTab();if(b)b.hidden=!visible;if(!visible)close()}
function mount(){if(document.getElementById('hct-open'))return;style();const b=document.createElement('button');b.id='hct-open';b.type='button';b.innerHTML='候補トレイ <span id="hct-count">0</span>';b.onclick=open;document.body.appendChild(b);requestSnapshot('mount');syncVisibility();new MutationObserver(syncVisibility).observe(document.documentElement,{attributes:true,subtree:true,attributeFilter:['class']});setInterval(syncVisibility,400)}
addEventListener(SNAPSHOT,e=>{snapshot=e.detail||{formationId:'',formationName:'',evaluationTypeId:'',items:[]};refreshButton();render()});
if(document.readyState==='loading')addEventListener('DOMContentLoaded',mount);else mount();
})();
