/* HADO Update09.5.22: normalized evidence for type-score judgement. */
(()=>{'use strict';
const root=typeof window!=='undefined'?window:globalThis;
const norm=v=>String(v??'').normalize('NFKC').replace(/\s+/g,'').toLowerCase();
const flat=v=>Array.isArray(v)?v.map(flat).join(' '):(v&&typeof v==='object'?Object.values(v).map(flat).join(' '):String(v??''));
const has=(text,words)=>words.some(w=>norm(text).includes(norm(w)));
const scopeLabel={self:'自部隊',ally:'味方',enemy:'敵部隊',unknown:'対象不明'};
const defs=[
['normal_attack_target_count_up','buff',['通常攻撃対象数','通常攻撃対象部隊数'],'count'],['normal_attack_power_up','buff',['通常攻撃威力']],['tactic_power_up','buff',['戦法威力']],['critical_tactic_rate_up','buff',['撃心発生','撃心発生率']],['critical_tactic_power_up','buff',['撃心威力']],['critical_rate_up','buff',['会心発生','会心発生率']],['critical_power_up','buff',['会心威力']],['attack_speed_up','buff',['攻撃速度']],['intelligence_up','buff',['知力上昇','知力を上昇','部隊の知力','知力']],['defense_up','buff',['防御上昇','防御を上昇','部隊の防御','防御']],['attack_up','buff',['攻撃上昇','攻撃を上昇','攻撃が上昇','部隊の攻撃','攻撃']],['range_up','range',['射程'],'count'],['anti_object_up','anti_object',['対物特効','対物特効を上昇']],
['enemy_anti_object_down','debuff',['敵部隊対物特効低下','対物特効低下','対物特効を低下']],['enemy_attack_down','debuff',['敵部隊攻撃低下','攻撃低下','攻撃を低下']],['enemy_defense_down','debuff',['敵部隊防御低下','防御低下','防御を低下']],['tactic_delay','debuff',['戦法遅延','戦法ゲージを減少','戦法ゲージを低下']],['chain_nullify_to_enemy','debuff',['連鎖無効を付与']],['confuse','debuff',['混乱']],['fear','debuff',['恐怖']],['severance','debuff',['分断']],['isolation','debuff',['絶縁']],
['weakening_nullify','disadvantage_counter',['弱化無効','弱化効果無効','弱化効果を無効']],['weakening_remove','disadvantage_counter',['弱化解除','弱化効果解除','弱化効果を解除','弱化回復','弱化効果を打ち消す','弱化効果を1つ打ち消す','弱化効果を打ち消し']],['weakening_avoid','disadvantage_counter',['弱化回避','弱化効果回避','弱化効果を避ける','弱化効果を避け','弱化効果を5%の確率で避ける','弱化効果を確率で避ける','弱化効果反射','弱化反射']],['status_nullify','disadvantage_counter',['状態変化無効','状態異常無効','不利変化無効','不利状態無効']],['status_remove','disadvantage_counter',['状態異常解除','不利状態解除','状態変化を解除']],['severance_counter','disadvantage_counter',['分断対策','分断を無効','分断を解除']],['isolation_counter','disadvantage_counter',['絶縁対策','絶縁を無効','絶縁を解除']],['chain_nullify_counter','disadvantage_counter',['連鎖無効対策','連鎖無効を無効','連鎖無効を解除']],['control_counter','disadvantage_counter',['同討対策','畏怖対策','轟然対策','疑心対策','制御対策']],['buff_protection','buff_protection',['強化解除回避','強化奪取回避','強化解除を回避','強化奪取を回避','バフ維持']],
['wounded_survival','survival',['負傷兵として生存する兵数','生存する兵数','負傷兵生存']],['annihilation_avoidance','survival',['壊滅回避','壊滅を回避']],['remaining_troops','survival',['残存兵力']],['wounded_recovery','recovery',['負傷兵回復','負傷兵を最大兵力','負傷兵を回復']],['healing','recovery',['兵力回復','兵力を回復','治癒']],['continuous_healing','recovery',['継続回復']],['damage_reduction','defense',['被ダメージ軽減','被ダメージを軽減','受けるダメージ-','ダメージ-']],['attribute_resistance','defense',['属性のダメージ','火属性のダメージ','水属性のダメージ','木属性のダメージ','金属性のダメージ','土属性のダメージ','属性耐性']],['troops_up','survival',['兵力上昇','兵力を上昇','部隊の兵力']],
['initial_tactic_gauge','gauge',['出陣時戦法ゲージ','初回戦法ゲージ']],['combat_start_tactic_gauge','gauge',['交戦開始時戦法ゲージ']],['tactic_gauge','gauge',['戦法ゲージを増加','戦法ゲージを上昇','戦法ゲージ']],['tactic_speed','gauge',['戦法速度']],['tactic_reduction','gauge',['戦法短縮']],['chain_rate','chain',['連鎖率','連鎖確率']]
].map(([family,kind,aliases,unit])=>({family,kind,aliases,unit}));
const aggregate=[/変化率集計/,/結果サマリー/,/パラメータサマリー/,/parameter_summary/i,/部隊の[^\s　]*(?:\(|（)?変化率集計/];
const derived=[/type-feature/i,/search-index/i,/related_link/i,/hadou_related_link_index/i,/semantic-owner/i,/direct-status/i,/derived/i,/型要素/,/検索タグ/,/関連リンク/];
function textOf(r){return flat([r?.rawText,r?.matchedText,r?.description,r?.effectText,r?.text,r?.condition,r?.key,r?.label,r?.statusEffectName,r?.sourceLabel,r?.featureId]);}
function sourceType(r,t){const x=String(r?.sourceType||r?.type||'').trim();if(x)return x;const s=`${r?.source||''} ${r?.sourceKind||''} ${r?.sourceLabel||''} ${t}`;if(/五行|火行|水行|木行|金行|土行/.test(s))return 'fiveElement';if(/軍馬|名馬|warhorse/i.test(s))return 'warhorse';if(/装備|武器|防具|文物|equipment/i.test(s))return 'equipment';if(/陣形|formation/i.test(s))return 'formation';if(/異文化|ethnic/i.test(s))return 'ethnicResearchSkill';if(/戦法|tactic/i.test(s))return 'tactic';return 'skill';}
function sourceSlot(r){const v=String(r?.sourceSlot||r?.slot||r?.roleId||r?.displayRole||'');if(/主将|main/.test(v))return 'main';if(/副将1|vice1|deputy1/.test(v))return 'vice1';if(/副将2|vice2|deputy2/.test(v))return 'vice2';if(/補佐1|support1/.test(v))return 'support1';if(/補佐2|support2/.test(v))return 'support2';if(/侍従|attendant/.test(v))return 'attendant';if(/装備|equipment/.test(v))return 'equipment';if(/五行|fiveElement/.test(v))return 'fiveElement';if(/陣形|formation/.test(v))return 'formation';if(/軍馬|名馬|warhorse/.test(v))return 'warhorse';return v||'unknown';}
function timing(r,t){const s=`${r?.timing||''} ${r?.timingLabel||''} ${r?.condition||''} ${t}`;if(has(s,['戦法発動時','戦法を発動','戦法発動','tactic']))return 'tactic_activated';if(has(s,['交戦開始時','戦闘開始時','combat_start']))return 'combat_start';if(has(s,['通常攻撃時','攻撃時','on_attack']))return 'on_attack';if(has(s,['ダメージを受け','攻撃を受け','壊滅しなかったとき','on_damaged']))return 'on_damaged';if(has(s,['連鎖時','連鎖した','on_chain']))return 'on_chain';if(has(s,['駐屯時','駐屯中','on_garrison']))return 'on_garrison';if(has(s,['常時','通常','normal','always']))return 'always';return 'conditional';}
function targetScope(r,t,def='unknown'){const x=String(r?.targetScope||r?.target||'').trim();if(['self','ally','enemy','unknown'].includes(x))return x;const raw=String(t||''),n=norm(raw);if(/(自身を含む味方|味方部隊|味方[0-9一二三四五六七八九十]*部隊|味方の|味方全体|味方)/.test(raw)||/自身を含む味方|味方/.test(n))return 'ally';if(/(自部隊|自身|自分|この武将|装備者|自身1部隊|自軍|部隊の)/.test(raw)||/(自部隊|自身|自分|装備者)/.test(n))return 'self';if(/(敵部隊|敵[0-9一二三四五六七八九十]*部隊|敵の|相手|対象部隊に)/.test(raw)||/敵|相手/.test(n))return 'enemy';return def;}
function targetCount(r,t){const v=Number(r?.targetCount||r?.target_count||0);if(Number.isFinite(v)&&v>0)return v;const m=String(t||'').match(/(?:味方|敵|自身)?\s*([0-9一二三四五六七八九十]+)\s*部隊/);if(!m)return null;return Number(m[1])||({一:1,二:2,三:3,四:4,五:5,六:6,七:7,八:8,九:9,十:10}[m[1]])||null;}
function valUnit(r,t,d){const rv=r?.value??r?.maxTotal??r?.amount;if(rv!==undefined&&rv!==null&&rv!==''){const n=Number(String(rv).replace(/[^0-9.+-]/g,''));if(Number.isFinite(n))return {value:n,unit:r?.unit||d?.unit||'%'};}const s=String(t||'').replace(/[−₋－―ー]/g,'-').replace(/＋/g,'+').replace(/％/g,'%');const p=s.match(/([+\-]?\d+(?:\.\d+)?)\s*%/);if(p)return {value:Number(p[1]),unit:'%'};const c=s.match(/[+\-]\s*(\d+(?:\.\d+)?)(?=\s*(?:部隊|回|個|人|対象|$))/);if(c)return {value:Number(c[1]),unit:d?.unit||'count'};return {value:null,unit:d?.unit||'presence'};}
function duration(r,t){const v=Number(r?.duration||r?.seconds||r?.effectDuration||0);if(Number.isFinite(v)&&v>0)return v;const m=String(t||'').match(/(\d+(?:\.\d+)?)\s*秒/);return m?Number(m[1]):null;}
function flags(r,t){const isAgg=!!(r?.isAggregateMetric||aggregate.some(p=>p.test(String(t||''))));const s=`${r?.source||''} ${r?.sourceKind||''} ${r?.sourcePartType||''} ${r?.featureType||''} ${r?.displayRole||''} ${t||''}`;const isDer=!!(r?.isDerivedTag||derived.some(p=>p.test(s)));return {isAgg,isDer};}
function families(t){const m=defs.filter(d=>has(t,d.aliases));const map=new Map();m.forEach(d=>{if(!map.has(d.family))map.set(d.family,d);});return [...map.values()];}
function normalizeRow(r,opt={}){const t=textOf(r);if(!t.trim())return [];const f=flags(r,t),src=sourceType(r,t),sid=String(r?.sourceId||r?.id||r?.featureId||r?.sourceLabel||src||''),sl=String(r?.sourceLabel||r?.name||r?.label||r?.featureId||src||''),slot=sourceSlot(r),tm=timing(r,t),scope=targetScope(r,t,opt.defaultTargetScope||'self'),cnt=targetCount(r,t),dur=duration(r,t);const fs=families(t);return (fs.length?fs:[{family:'unknown',kind:'utility'}]).map((d,i)=>{const vu=valUnit(r,t,d),key=[src,sid,slot,tm,scope,d.family,String(r?.condition||'')].map(norm).join('|'),primary=!f.isAgg&&!f.isDer&&d.family!=='unknown';return {evidenceId:`${key}|${i}`,sourceType:src,sourceId:sid,sourceLabel:sl,sourceSlot:slot,timing:tm,conditionText:String(r?.condition||r?.conditionText||''),targetScope:scope,targetScopeLabel:scopeLabel[scope]||scopeLabel.unknown,targetCount:cnt,effectKind:d.kind||'utility',effectFamily:d.family,value:vu.value,unit:vu.unit,duration:dur,isPrimaryEffect:primary,isDerivedTag:f.isDer,isAggregateMetric:f.isAgg,evidenceGroupKey:key,rawText:String(r?.rawText||r?.matchedText||t),sourceRaw:r};});}
function collectArray(out,v){if(Array.isArray(v))out.push(...v.filter(Boolean));}
function collectCandidateRows(f={},ctx={}){const d=ctx.formationData||ctx.data||f.formationData||{},out=[];['scoreEvidenceSourceRows','effects','effectsRaw','typeFeatures','statusEffectRefs'].forEach(k=>collectArray(out,f[k]));['effects','effectsRaw','skills','fiveElements'].forEach(k=>collectArray(out,d[k]));['effects','skills','fiveElements'].forEach(k=>collectArray(out,ctx[k]));const sum=d.summary||ctx.summary||f.summary;if(sum&&typeof sum==='object')Object.entries(sum).forEach(([tm,gs])=>gs&&typeof gs==='object'&&Object.entries(gs).forEach(([g,ps])=>ps&&typeof ps==='object'&&Object.entries(ps).forEach(([k,v])=>out.push({sourceType:'summary',sourceKind:'aggregate',timing:tm,group:g,key:k,label:`${k}(変化率集計)`,value:v?.maxTotal??v?.value,unit:v?.unit,rawText:`${k}(変化率集計)`,isAggregateMetric:true}))));return out;}
function dedupe(rows){const seen=new Set(),out=[];rows.forEach(r=>{const k=r.evidenceGroupKey||r.evidenceId;if(seen.has(k))return;seen.add(k);out.push(r);});return out;}
function buildFormationScoreEvidence(f={},ctx={}){const sources=collectCandidateRows(f,ctx),evidence=dedupe(sources.flatMap(r=>normalizeRow(r,ctx)));root.HadoTypeScoreEvidence.lastEvidence={schemaVersion:'scoreEvidence-v1',generatedAt:new Date().toISOString(),formationId:f?.id||'',formationName:f?.name||'',sourceRowCount:sources.length,evidenceCount:evidence.length,primaryEvidenceCount:evidence.filter(r=>r.isPrimaryEffect).length,evidence};return evidence;}
function summarizeEvidence(evidence){return (Array.isArray(evidence)?evidence:[]).reduce((a,r)=>(a[r.effectFamily||'unknown']=(a[r.effectFamily||'unknown']||0)+1,a),{});}
const api={FAMILY_DEFINITIONS:defs,TARGET_SCOPE_LABELS:scopeLabel,buildFormationScoreEvidence,collectCandidateRows,normalizeRow,matchedFamilies:families,inferTargetScope:targetScope,inferTargetCount:targetCount,inferTiming:timing,summarizeEvidence,lastEvidence:null};
root.HadoTypeScoreEvidence=api;if(typeof module!=='undefined'&&module.exports)module.exports=api;
})();
