/* HADO app type candidates: saved-mode aware selectable type candidates and type-based new formation creation */
(()=>{'use strict';
const KEY='hado.typeEntry.selection.v1',EV='hado:type-search-entry-selected',FILES=['hadou_type_search_role_index.json','hadou_type_score_rules.json','hadou_type_purpose_rules.json'];
const ROLES=[['main_general','主将'],['vice_general','副将'],['support_general','補佐'],['attendant','侍従'],['equipment','装備'],['formation','陣形'],['siege_weapon','兵器'],['warhorse','名馬'],['warhorse_skill','軍馬技能']];
const st={data:null,role:'main_general',q:'',sel:null,picked:''};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=s=>String(s??'').normalize('NFKC').replace(/\s+/g,'').toLowerCase();
const saveName=s=>String(s??'').normalize('NFKC').trim();
function savedMatchKey(s){let v=saveName(s);try{if(typeof normalizeSaveItemName==='function')v=normalizeSaveItemName(v)}catch{}return saveName(v).replace(/^【三國志\s*覇道】/,'').replace(/^【[^】]+】/,'')}
function savedNameSetHas(set,name){const key=savedMatchKey(name);if(!key)return false;for(const owned of set||[]){if(savedMatchKey(owned)===key)return true}return false}
const flat=v=>Array.isArray(v)?v.map(flat).join(' '):(v&&typeof v==='object'?Object.values(v).map(flat).join(' '):String(v??''));
const items=(v,ks)=>{if(Array.isArray(v))return v;for(const k of ks)if(Array.isArray(v?.[k]))return v[k];return[]};
const loadSel=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'null')}catch{return null}};
const fetchJson=async f=>{const r=await fetch(f,{cache:'no-store'});if(!r.ok)throw Error(`${f}: HTTP ${r.status}`);return r.json()};
const type=()=>st.data?.types.find(v=>v.typeId===st.sel?.typeId);
const purpose=()=>st.data?.purposes.find(v=>v.purposeId===st.sel?.purposeId);
function displayVersion(){return window.HADO_APP_DISPLAY_VERSION||window.HADO_APP_VERSION_META?.displayVersion||'3.0.0.0'}
function score(x){if(!window.HadoTypeScore)throw Error('適合スコア共通処理が読み込まれていません。');return window.HadoTypeScore.score(x,type())}
function appState(){try{return typeof state==='object'?state:null}catch{return null}}
function savedModeActive(){return appState()?.viewMode==='saved'}
function currentSave(){try{return typeof getCurrentSave==='function'?getCurrentSave():null}catch{return null}}
function savedIndex(){return appState()?.savedModeIndex||{generalNames:new Set(),equipmentNames:new Set()}}
function savedCandidateAllowed(v){if(!savedModeActive())return true;const idx=savedIndex(),name=canonicalName(v)||displayName(v);if(!savedMatchKey(name))return false;if(['main_general','vice_general','support_general','attendant'].includes(v.roleId))return savedNameSetHas(idx.generalNames,name);if(v.roleId==='equipment')return savedNameSetHas(idx.equipmentNames,name);if(v.roleId==='warhorse'||v.roleId==='warhorse_skill'){try{return Object.keys(getCurrentWarhorseData()?.owned||{}).length>0}catch{return false}}return true}
function savedCandidateNote(){if(!savedModeActive())return '全データ表示: 全武将・全装備・全名馬などを候補対象にします。';const save=currentSave();return `保存データ表示: ${esc(save?.name||'保存データ')} の所有武将・装備・名馬に候補を限定し、将星/装備段階などの保存設定は既存評価処理へ反映されます。`}
function roleRows(role){const q=norm(st.q);return st.data.roles.filter(v=>v.roleId===role).map(v=>({...v,_s:score(v)})).filter(v=>v._s.matchedCount>0).filter(savedCandidateAllowed).filter(v=>!q||norm(flat([v.displayName,v.name,v.typeFeatures,v.statusEffectRefs])).includes(q)).sort((a,b)=>b._s.confirmedScore-a._s.confirmedScore||b._s.conditionalMaxScore-a._s.conditionalMaxScore||Number(a.sourceIndex||0)-Number(b.sourceIndex||0))}
function rows(){return roleRows(st.role)}
function rowKey(v){return `${v?.roleId||st.role}::${canonicalName(v)||displayName(v)}`}
function togglePick(key){st.picked=st.picked===key?'':key;render()}
function chipLabel(x){if(x==null)return '';if(typeof x==='string'||typeof x==='number')return String(x);if(Array.isArray(x))return x.map(chipLabel).filter(Boolean).join(' / ');if(typeof x==='object')return String(x.label||x.statusEffectName||x.displayName||x.name||x.featureId||'');return ''}
function chipLabels(v){return [...new Set([...(v.typeFeatures||[]),...(v.statusEffectRefs||[])].map(chipLabel).filter(Boolean))]}
function canonicalName(v){return String(v?.name||v?.displayName||'').trim()}
function displayName(v){return String(v?.displayName||v?.name||'').trim()}
function selectionReason(){const p=purpose();if(!p)return '';const rs=[...(p.primaryTypes||[]).map(v=>({...v,roleLabel:'主軸理由'})),...(p.secondaryTypes||[]).map(v=>({...v,roleLabel:'補助理由'}))];const row=rs.find(v=>v.typeId===st.sel?.typeId);return row?.reason?`${row.roleLabel}: ${row.reason}`:''}
function style(){if(document.getElementById('htc-style'))return;const e=document.createElement('style');e.id='htc-style';e.textContent=`#htc-open{position:fixed;right:18px;bottom:72px;z-index:99990;border:1px solid #1d4ed8;border-radius:999px;padding:11px 17px;background:#fff;color:#1d4ed8;font-weight:700;cursor:pointer}#htc-open:disabled{opacity:.5}#htc-overlay{position:fixed;inset:0;z-index:99992;background:#0f172a94;display:flex;align-items:center;justify-content:center;padding:16px}#htc-modal{width:min(1040px,100%);max-height:92dvh;background:#fff;border-radius:18px;display:grid;grid-template-rows:auto auto auto minmax(0,1fr);overflow:hidden;color:#172033}.htc-p{padding:14px 18px}.htc-head{display:flex;justify-content:space-between;gap:10px}.htc-actions{display:flex;gap:8px;flex-wrap:wrap}.htc-tabs{display:flex;gap:7px;flex-wrap:wrap;background:#f8fafc}.htc-btn,.htc-tab{border:1px solid #cbd5e1;background:#fff;border-radius:10px;padding:8px 11px;cursor:pointer}.htc-btn.primary{background:#1d4ed8;border-color:#1d4ed8;color:#fff}.htc-tab.on{border-color:#2563eb;background:#eff6ff;color:#1d4ed8;font-weight:700}.htc-search{width:100%;padding:10px;border:1px solid #cbd5e1;border-radius:10px}.htc-body{overflow:auto}.htc-list{display:grid;gap:8px}.htc-item{border:1px solid #d8e0eb;border-radius:12px;padding:11px;cursor:pointer;background:#fff;transition:background .15s,border-color .15s,box-shadow .15s}.htc-item:hover{border-color:#93c5fd;background:#f8fbff}.htc-item.on{border-color:#2563eb;background:#dbeafe;box-shadow:0 0 0 2px #bfdbfe inset}.htc-picked{display:inline-block;margin-left:8px;border-radius:999px;background:#1d4ed8;color:#fff;font-size:11px;padding:2px 7px;vertical-align:middle}.htc-title{font-weight:700}.htc-note,.htc-detail,.htc-score{font-size:12px;color:#64748b;line-height:1.55;margin-top:4px}.htc-score{font-weight:700;color:#334155}.htc-score strong{font-size:15px;color:#0f766e}.htc-chip{display:inline-block;border-radius:999px;padding:2px 7px;background:#eef2ff;color:#3730a3;margin:2px 4px 0 0}@media(max-width:720px){#htc-overlay{padding:0}#htc-modal{width:100%;height:100dvh;max-height:none;border-radius:0}}`;document.head.appendChild(e)}
function close(){document.getElementById('htc-overlay')?.remove()}
function createFromType(){if(typeof window.createFormationFromTypeSelection!=='function')return alert('新規部隊作成処理が読み込まれていません。');const f=window.createFormationFromTypeSelection({...st.sel,typeName:type()?.typeName||st.sel?.typeName||''});if(f)close()}
function render(){const m=document.getElementById('htc-modal'),rs=rows(),reason=selectionReason();m.innerHTML=`<div class="htc-p htc-head"><div><h2>型候補一覧</h2><div class="htc-note">${esc(displayVersion())} / 選択中の型: ${esc(type()?.typeName||'未選択')} / 目的: ${esc(purpose()?.purposeName||'指定なし')}</div>${reason?`<div class="htc-note">${esc(reason)}</div>`:''}<div class="htc-note">${savedCandidateNote()}</div><div class="htc-note">候補をクリックすると選択状態になります。同じ候補を再クリックすると選択解除します。</div></div><div class="htc-actions"><button class="htc-btn primary" data-create-formation>この型で新規部隊</button><button class="htc-btn" data-close>閉じる</button></div></div><div class="htc-p htc-tabs">${ROLES.map(([id,l])=>`<button class="htc-tab ${st.role===id?'on':''}" data-role="${id}">${l} (${roleRows(id).length})</button>`).join('')}</div><div class="htc-p"><input id="htc-q" class="htc-search" placeholder="名称・特徴で絞り込み" value="${esc(st.q)}"></div><div class="htc-p htc-body"><div class="htc-list">${rs.map(v=>{const k=rowKey(v),picked=st.picked===k;return `<div class="htc-item ${picked?'on':''}" role="button" tabindex="0" aria-pressed="${picked?'true':'false'}" data-pick-key="${esc(k)}" data-role-id="${esc(v.roleId||st.role)}" data-canonical-name="${esc(canonicalName(v))}" data-display-name="${esc(displayName(v))}"><div class="htc-title">${esc(displayName(v))}${picked?'<span class="htc-picked">選択中</span>':''}</div><div class="htc-score">適合スコア: <strong>${esc(window.HadoTypeScore.label(v._s))}</strong></div><div class="htc-detail">${esc(window.HadoTypeScore.summary(v._s))}</div><div class="htc-detail">${chipLabels(v).map(x=>`<span class="htc-chip">${esc(x)}</span>`).join('')}</div></div>`}).join('')||'<div class="htc-note">該当候補がありません。</div>'}</div></div>`;m.querySelectorAll('[data-close]').forEach(b=>b.onclick=close);m.querySelector('[data-create-formation]').onclick=createFromType;m.querySelectorAll('[data-role]').forEach(b=>b.onclick=()=>{st.role=b.dataset.role;st.q='';render()});m.querySelectorAll('[data-pick-key]').forEach(card=>{card.onclick=()=>togglePick(card.dataset.pickKey);card.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();togglePick(card.dataset.pickKey)}}});m.querySelector('#htc-q').oninput=e=>{st.q=e.target.value;render()}}
async function open(){st.sel=loadSel();if(!st.sel?.typeId)return alert('型編成ナビで型を選択し、「選択を保存」を押してください。');if(!st.data){const[a,b,c]=await Promise.all(FILES.map(fetchJson));st.data={roles:items(a,['items']),types:items(b,['items','types']),purposes:items(c,['items','purposes'])}}if(!type())throw Error(`選択中の型が見つかりません: ${st.sel.typeId}`);close();const o=document.createElement('div');o.id='htc-overlay';o.innerHTML='<section id="htc-modal"></section>';o.onclick=e=>{if(e.target===o)close()};document.body.appendChild(o);render()}
function isFormationTab(){const stt=appState();return stt?stt.mainTab==='formation':document.getElementById('formationScreen')&&!document.getElementById('formationScreen').classList.contains('tab-content-hidden')}
function syncVisibility(){const b=document.getElementById('htc-open');const visible=!!isFormationTab();if(b)b.hidden=!visible;if(!visible)close()}
function refresh(){const b=document.getElementById('htc-open');if(b)b.disabled=!loadSel()?.typeId;syncVisibility()}
function mount(){style();const b=document.createElement('button');b.id='htc-open';b.textContent='型候補一覧';b.onclick=()=>open().catch(e=>alert(`型候補一覧の読込に失敗しました。\n${e.message}`));document.body.appendChild(b);refresh();addEventListener(EV,refresh);addEventListener('storage',refresh);new MutationObserver(syncVisibility).observe(document.documentElement,{attributes:true,subtree:true,attributeFilter:['class']});setInterval(syncVisibility,400)}
if(document.readyState==='loading')addEventListener('DOMContentLoaded',mount);else mount();
})();
