/* HADO app 3.0.0.0 candidate tray core */
(()=>{'use strict';
const EV={add:'hado:formation-candidate-tray-add',request:'hado:formation-candidate-tray-snapshot-request',snapshot:'hado:formation-candidate-tray-snapshot',remove:'hado:formation-candidate-tray-remove',clear:'hado:formation-candidate-tray-clear',place:'hado:formation-candidate-tray-place'};
const TYPE_KEY='hado.typeEntry.selection.v1';
const norm=v=>String(v??'').normalize('NFKC').trim();
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const current=()=>getCurrentFormation();
const clean=v=>sanitizeFormationCandidateTray(v||[]);
function publish(){const f=current();dispatchEvent(new CustomEvent(EV.snapshot,{detail:{formationId:f?.id||'',formationName:f?.name||'',evaluationTypeId:f?.evaluationTypeId||'',items:clean(f?.candidateTray)}}))}
function persist(context){const f=current();if(f){f.updatedAt=new Date().toISOString();state.formationDirty=true}saveFormationDataToStorage(context);publish()}
function selectedType(){try{return JSON.parse(localStorage.getItem(TYPE_KEY)||'{}')}catch{return{}}}
function idFor(v){return ['tray',v.roleId,v.typeId,v.name].map(norm).join('_').replace(/[^\w\u3000-\u9fff\u3040-\u30ff-]/g,'_')}
function add(detail){const f=ensureCurrentFormation(),s=selectedType();const raw=norm(detail.canonicalName||detail.name||detail.displayName);const row={roleId:norm(detail.roleId),name:normalizeSaveItemName(raw),displayName:norm(detail.displayName||detail.name||raw),typeId:norm(detail.typeId||s.typeId),typeName:norm(detail.typeName||s.typeName||s.typeId),source:'型候補一覧',addedAt:new Date().toISOString()};row.id=idFor(row);if(!row.roleId||!row.name)return;f.evaluationTypeId=row.typeId||f.evaluationTypeId;f.candidateTray=clean(f.candidateTray);if(!f.candidateTray.some(v=>v.id===row.id))f.candidateTray.push(row);persist('candidateTray:add')}
function remove(id){const f=current();if(!f)return;f.candidateTray=clean(f.candidateTray).filter(v=>v.id!==norm(id));persist('candidateTray:remove')}
function clear(){const f=current();if(!f)return;f.candidateTray=[];persist('candidateTray:clear')}
function ownedHorses(){try{return Object.values(getCurrentWarhorseData()?.owned||{}).map(wh=>({item:wh,id:norm(wh?.id),name:norm(wh?.name||wh?.customName),label:getWarhorseAssignmentOptionLabel(wh)})).filter(v=>v.id)}catch{return[]}}
function horseMasterName(wh){try{return norm(getWarhorseMasterById(wh?.horseMasterId)?.name)}catch{return''}}
function horseByCandidate(name){const n=norm(name);return ownedHorses().find(v=>v.id===n||v.name===n||v.label===n||horseMasterName(v.item)===n)||null}
function horseBySkill(name){const n=norm(name);return ownedHorses().find(v=>norm(JSON.stringify([v.item,getWarhorseMasterById(v.item?.horseMasterId)])).includes(n))||null}
function pickHorse(row){const wh=row.roleId==='warhorse_skill'?horseBySkill(row.name):horseByCandidate(row.name);if(!wh)return alert(row.roleId==='warhorse_skill'?'この軍馬技能を持つ所有済み軍馬が見つかりません。':'所有済み軍馬が見つかりません。');document.getElementById('hctp')?.remove();setMainTab('formation');const o=document.createElement('div');o.id='hctp';o.style='position:fixed;inset:0;z-index:99995;background:#0f172a94;display:flex;align-items:center;justify-content:center;padding:16px';o.innerHTML=`<section style="width:min(620px,100%);background:#fff;border-radius:16px;padding:16px"><h2>軍馬枠を選択</h2><p>${esc(wh.label||wh.name||row.name)} を登録します。</p>${[0,1,2].map(i=>`<button data-horse-slot="${i}">軍馬${i+1}</button>`).join(' ')} <button data-x>閉じる</button></section>`;document.body.appendChild(o);o.querySelector('[data-x]').onclick=()=>o.remove();o.querySelectorAll('[data-horse-slot]').forEach(b=>b.onclick=()=>{setFormationWarhorseSlot(Number(b.dataset.horseSlot),wh.id);o.remove()})}
function setFormation(row){const f=current();if(!f)return;const name=normalizeFormationMasterName(row.name);if(!(state.formationMasters||[]).some(item=>norm(item?.name||item?.title)===name))return alert('陣形候補が見つかりません。');f.formationName=name;repairFormationJijuAssignments(f,'candidateTray:formation');persist('candidateTray:formation');renderFormationScreen()}
function setSiege(row){const f=current();if(!f)return;const name=normalizeSaveItemName(row.name);if(!(state.siegeWeapons||[]).some(item=>normalizeSaveItemName(getItemDisplayName(item))===name))return alert('兵器候補が見つかりません。');f.siegeWeapon={name,level:normalizeFormationExtensionLevel('siegeWeapon',name,0)};persist('candidateTray:siegeWeapon');renderFormationScreen()}
function destinations(row){const f=current(),out=[],push=(label,type,slotKey,equipKey='')=>out.push({label,type,slotKey,equipKey});if(row.roleId==='main_general')push('主将','general','main');if(row.roleId==='vice_general'){push('副将1','general','deputy1');push('副将2','general','deputy2')}if(row.roleId==='support_general'){push('補佐1','general','support1');push('補佐2','general','support2')}if(row.roleId==='attendant')FORMATION_SLOT_SPECS.forEach(s=>{if(f.slots?.[s.key]?.general)push(`${s.label}の侍従`,'attendant',s.key)});if(row.roleId==='equipment')FORMATION_SLOT_SPECS.forEach(s=>{if(f.slots?.[s.key]?.general)EQUIP_SLOT_SPECS.forEach(e=>push(`${s.label} → ${e.label}`,'equipment',s.key,e.key))});return out}
function aliasSet(item){return [getItemDisplayName(item),item?.name,item?.displayName,item?.rawName,item?.title,item?.raw?.name,item?.raw?.title].map(v=>normalizeSaveItemName(norm(v))).filter(Boolean)}
function resolveName(category,row){const wanted=[row.name,row.displayName].map(v=>normalizeSaveItemName(norm(v))).filter(Boolean);const items=formationAllowedItems(category);for(const item of items){const aliases=aliasSet(item);if(wanted.some(v=>aliases.includes(v)))return getItemDisplayName(item)}return row.displayName||row.name||''}
function handoff(row,dest){document.getElementById('hctp')?.remove();setMainTab('formation');state.formationSelectedSlot=dest.slotKey;state.formationSelectorDialog={type:dest.type,slotKey:dest.slotKey,equipKey:dest.equipKey||'',advisorKey:'',jijuPosition:'',keyword:'',advisorSkill:'',statusGroup:'',statusEffect:'',troop:'',rarity:'',equipmentType:''};const category=dest.type==='equipment'?'equipments':'generals';assignFormationSelectorCandidate(category,resolveName(category,row))}
function place(id){const row=clean(current()?.candidateTray).find(v=>v.id===norm(id));if(!row)return;if(row.roleId==='formation')return setFormation(row);if(row.roleId==='siege_weapon')return setSiege(row);if(row.roleId==='warhorse'||row.roleId==='warhorse_skill')return pickHorse(row);const list=destinations(row);if(!list.length)return alert('配置先候補がありません。');const o=document.createElement('div');o.id='hctp';o.style='position:fixed;inset:0;z-index:99995;background:#0f172a94;display:flex;align-items:center;justify-content:center;padding:16px';o.innerHTML=`<section style="width:min(620px,100%);background:#fff;border-radius:16px;padding:16px"><h2>配置先を選択</h2><p>${esc(row.displayName||row.name)} を登録します。</p>${list.map((v,i)=>`<button data-d="${i}">${esc(v.label)}</button>`).join(' ')} <button data-x>閉じる</button></section>`;document.body.appendChild(o);o.querySelector('[data-x]').onclick=()=>o.remove();o.querySelectorAll('[data-d]').forEach(b=>b.onclick=()=>handoff(row,list[Number(b.dataset.d)]))}
function patchCards(){document.querySelectorAll('#htc-modal [data-tray-add]').forEach(button=>button.remove())}
addEventListener(EV.add,e=>add(e.detail||{}));addEventListener(EV.request,publish);addEventListener(EV.remove,e=>remove(e.detail?.id));addEventListener(EV.clear,clear);addEventListener(EV.place,e=>place(e.detail?.id));new MutationObserver(patchCards).observe(document.documentElement,{childList:true,subtree:true});patchCards();publish();
})();
