/* HADO app 3.0.0.0 candidate tray core */
(()=>{'use strict';
const EV={add:'hado:formation-candidate-tray-add',request:'hado:formation-candidate-tray-snapshot-request',snapshot:'hado:formation-candidate-tray-snapshot',remove:'hado:formation-candidate-tray-remove',clear:'hado:formation-candidate-tray-clear',place:'hado:formation-candidate-tray-place'};
const TYPE_KEY='hado.typeEntry.selection.v1';
const normText=v=>String(v??'').normalize('NFKC').trim();
const escapeHtml=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const formation=()=>getCurrentFormation();
const sanitize=v=>sanitizeFormationCandidateTray(v||[]);
function publish(){const f=formation();dispatchEvent(new CustomEvent(EV.snapshot,{detail:{formationId:f?.id||'',formationName:f?.name||'',evaluationTypeId:f?.evaluationTypeId||'',items:sanitize(f?.candidateTray)}}))}
function persist(context){const f=formation();if(f){f.updatedAt=new Date().toISOString();state.formationDirty=true}saveFormationDataToStorage(context);publish()}
function selectedType(){try{return JSON.parse(localStorage.getItem(TYPE_KEY)||'{}')}catch{return{}}}
function trayId(v){return ['tray',v.roleId,v.typeId,v.name].map(normText).join('_').replace(/[^\w\u3000-\u9fff\u3040-\u30ff-]/g,'_')}
function add(detail){const f=ensureCurrentFormation(),selected=selectedType();const row={roleId:normText(detail.roleId),name:normalizeSaveItemName(detail.name),typeId:normText(detail.typeId||selected.typeId),typeName:normText(detail.typeName||selected.typeName||selected.typeId),source:'型候補一覧',addedAt:new Date().toISOString()};row.id=trayId(row);if(!row.roleId||!row.name)return;f.evaluationTypeId=row.typeId||f.evaluationTypeId;f.candidateTray=sanitize(f.candidateTray);if(!f.candidateTray.some(v=>v.id===row.id))f.candidateTray.push(row);persist('candidateTray:add')}
function remove(id){const f=formation();if(!f)return;f.candidateTray=sanitize(f.candidateTray).filter(v=>v.id!==normText(id));persist('candidateTray:remove')}
function clear(){const f=formation();if(!f)return;f.candidateTray=[];persist('candidateTray:clear')}
function ownedWarhorseRows(){try{const data=getCurrentWarhorseData();return Object.values(data?.owned||{}).map(wh=>({item:wh,id:normText(wh?.id||''),name:normText(wh?.name||wh?.customName||''),label:getWarhorseAssignmentOptionLabel(wh)})).filter(v=>v.id)}catch{return[]}}
function warhorseMasterName(wh){try{return normText(getWarhorseMasterById(wh?.horseMasterId)?.name||'')}catch{return''}}
function findOwnedWarhorseByCandidate(name){const n=normText(name);return ownedWarhorseRows().find(row=>row.id===n||row.name===n||row.label===n||warhorseMasterName(row.item)===n)||null}
function findOwnedWarhorseBySkill(name){const n=normText(name);return ownedWarhorseRows().find(row=>normText(JSON.stringify([row.item,getWarhorseMasterById(row.item?.horseMasterId)])).includes(n))||null}
function openWarhorseSlotPicker(row){const wh=row.roleId==='warhorse_skill'?findOwnedWarhorseBySkill(row.name):findOwnedWarhorseByCandidate(row.name);if(!wh)return alert(row.roleId==='warhorse_skill'?'この軍馬技能を持つ所有済み軍馬が見つかりません。対象軍馬を登録してください。':'所有済み軍馬が見つかりません。保存データに名馬を登録してください。');document.getElementById('hctp')?.remove();setMainTab('formation');const overlay=document.createElement('div');overlay.id='hctp';overlay.style='position:fixed;inset:0;z-index:99995;background:#0f172a94;display:flex;align-items:center;justify-content:center;padding:16px';overlay.innerHTML=`<section style="width:min(620px,100%);background:#fff;border-radius:16px;padding:16px"><h2>軍馬枠を選択</h2><p>${escapeHtml(wh.label||wh.name||row.name)} は既存の軍馬割当処理で登録します。同じ軍馬を複数枠へ割り当てることはできません。</p>${[0,1,2].map(i=>`<button data-horse-slot="${i}">軍馬${i+1}</button>`).join(' ')} <button data-x>閉じる</button></section>`;document.body.appendChild(overlay);overlay.querySelector('[data-x]').onclick=()=>overlay.remove();overlay.querySelectorAll('[data-horse-slot]').forEach(b=>b.onclick=()=>{setFormationWarhorseSlot(Number(b.dataset.horseSlot),wh.id);overlay.remove();});}
function setFormationMaster(row){const f=formation();if(!f)return;const name=normalizeFormationMasterName(row.name);if(!(state.formationMasters||[]).some(item=>normText(item?.name||item?.title||'')===name))return alert('陣形候補が見つかりません。');f.formationName=name;repairFormationJijuAssignments(f,'candidateTray:formation');persist('candidateTray:formation');renderFormationScreen()}
function setSiegeWeapon(row){const f=formation();if(!f)return;const name=normalizeSaveItemName(row.name);if(!(state.siegeWeapons||[]).some(item=>normalizeSaveItemName(getItemDisplayName(item))===name))return alert('兵器候補が見つかりません。');f.siegeWeapon={name,level:normalizeFormationExtensionLevel('siegeWeapon',name,0)};persist('candidateTray:siegeWeapon');renderFormationScreen()}
function destinations(row){const f=formation(),out=[],push=(label,type,slotKey,equipKey='')=>out.push({label,type,slotKey,equipKey});if(row.roleId==='main_general')push('主将','general','main');if(row.roleId==='vice_general'){push('副将1','general','deputy1');push('副将2','general','deputy2')}if(row.roleId==='support_general'){push('補佐1','general','support1');push('補佐2','general','support2')}if(row.roleId==='attendant')FORMATION_SLOT_SPECS.forEach(s=>{if(f.slots?.[s.key]?.general)push(`${s.label}の侍従`,'attendant',s.key)});if(row.roleId==='equipment')FORMATION_SLOT_SPECS.forEach(s=>{if(f.slots?.[s.key]?.general)EQUIP_SLOT_SPECS.forEach(e=>push(`${s.label} → ${e.label}`,'equipment',s.key,e.key))});return out}
function handoff(row,dest){document.getElementById('hctp')?.remove();setMainTab('formation');state.formationSelectedSlot=dest.slotKey;state.formationSelectorDialog={type:dest.type,slotKey:dest.slotKey,equipKey:dest.equipKey||'',advisorKey:'',jijuPosition:'',keyword:'',advisorSkill:'',statusGroup:'',statusEffect:'',troop:'',rarity:'',equipmentType:''};assignFormationSelectorCandidate(dest.type==='equipment'?'equipments':'generals',row.name)}
function place(id){const row=sanitize(formation()?.candidateTray).find(v=>v.id===normText(id));if(!row)return;if(row.roleId==='formation')return setFormationMaster(row);if(row.roleId==='siege_weapon')return setSiegeWeapon(row);if(row.roleId==='warhorse'||row.roleId==='warhorse_skill')return openWarhorseSlotPicker(row);const list=destinations(row);if(!list.length)return alert('配置先候補がありません。必要な部隊枠を先に設定してください。');const overlay=document.createElement('div');overlay.id='hctp';overlay.style='position:fixed;inset:0;z-index:99995;background:#0f172a94;display:flex;align-items:center;justify-content:center;padding:16px';overlay.innerHTML=`<section style="width:min(620px,100%);background:#fff;border-radius:16px;padding:16px"><h2>配置先を選択</h2><p>${escapeHtml(row.name)} は既存の成立判定を通して登録します。</p>${list.map((v,i)=>`<button data-d="${i}">${escapeHtml(v.label)}</button>`).join(' ')} <button data-x>閉じる</button></section>`;document.body.appendChild(overlay);overlay.querySelector('[data-x]').onclick=()=>overlay.remove();overlay.querySelectorAll('[data-d]').forEach(b=>b.onclick=()=>handoff(row,list[Number(b.dataset.d)]))}
function patchCandidateCards(){document.querySelectorAll('#htc-modal .htc-item').forEach(card=>{if(card.querySelector('[data-tray-add]'))return;const name=normText(card.querySelector('.htc-title')?.textContent);if(!name)return;const button=document.createElement('button');button.type='button';button.dataset.trayAdd='1';button.className='htc-btn';button.textContent='候補トレイへ追加';button.onclick=e=>{e.preventDefault();e.stopPropagation();add({roleId:document.querySelector('#htc-modal .htc-tab.on')?.dataset.role||'',name})};card.appendChild(button)})}
addEventListener(EV.add,e=>add(e.detail||{}));addEventListener(EV.request,publish);addEventListener(EV.remove,e=>remove(e.detail?.id));addEventListener(EV.clear,clear);addEventListener(EV.place,e=>place(e.detail?.id));new MutationObserver(patchCandidateCards).observe(document.documentElement,{childList:true,subtree:true});patchCandidateCards();publish();
})();
