/* HADO app type candidates Update08.23: cache saved-mode candidate rendering and async diagnostics */
(()=>{'use strict';
const KEY='hado.typeEntry.selection.v1',EV='hado:type-search-entry-selected',FILES=['hadou_type_search_role_index.json','hadou_type_score_rules.json','hadou_type_purpose_rules.json'];
const ROLES=[['main_general','主将'],['vice_general','副将'],['support_general','補佐'],['attendant','侍従'],['equipment','装備'],['formation','陣形'],['siege_weapon','兵器'],['warhorse','名馬'],['warhorse_skill','軍馬技能']];
const st={data:null,role:'main_general',q:'',sel:null,picked:'',roleCache:new Map(),roleBaseCache:new Map(),diagnosticQueue:[],diagnosticTimer:0};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=s=>String(s??'').normalize('NFKC').replace(/\s+/g,'').toLowerCase();
const saveName=s=>String(s??'').normalize('NFKC').trim();
const removeReading=s=>String(s??'').replace(/[（(][ぁ-ゖァ-ヺー・\s]+[）)]/g,'');
function savedMatchKey(s){let v=saveName(s);try{if(typeof normalizeSaveItemName==='function')v=normalizeSaveItemName(v)}catch{}return removeReading(saveName(v).replace(/^【三國志\s*覇道】/,'').replace(/^【[^】]+】/,'')).trim()}
function savedNameSetHas(set,name){const key=savedMatchKey(name);if(!key)return false;for(const owned of set||[]){if(savedMatchKey(owned)===key)return true}return false}
function addSavedNames(out,values){(values||[]).forEach(v=>{const n=savedMatchKey(v);if(n)out.add(n)});return out}
const flat=v=>Array.isArray(v)?v.map(flat).join(' '):(v&&typeof v==='object'?Object.values(v).map(flat).join(' '):String(v??''));
const items=(v,ks)=>{if(Array.isArray(v))return v;for(const k of ks)if(Array.isArray(v?.[k]))return v[k];return[]};
const loadSel=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'null')}catch{return null}};
const fetchJson=async f=>{const r=await fetch(f,{cache:'no-store'});if(!r.ok)throw Error(`${f}: HTTP ${r.status}`);return r.json()};
const type=()=>st.data?.types.find(v=>v.typeId===st.sel?.typeId);
const purpose=()=>st.data?.purposes.find(v=>v.purposeId===st.sel?.purposeId);
function displayVersion(){return window.HADO_APP_DISPLAY_VERSION||window.HADO_APP_VERSION_META?.displayVersion||'3.0.0.0'}
function score(x){if(!window.HadoTypeScore)throw Error('適合スコア共通処理が読み込まれていません。');return window.HadoTypeScore.score(savedScoreEntity(x),type())}
function scoreCandidate(x){if(!window.HadoTypeScore)throw Error('適合スコア共通処理が読み込まれていません。');const entity=savedScoreEntity(x),prev=window.HADO_TYPE_SCORE_TRACE_SUSPENDED;window.HADO_TYPE_SCORE_TRACE_SUSPENDED=true;try{return {...x,_savedTypeCandidateAudit:entity._savedTypeCandidateAudit||null,_s:window.HadoTypeScore.score(entity,type())}}finally{window.HADO_TYPE_SCORE_TRACE_SUSPENDED=prev}}
function appState(){try{return typeof state==='object'?state:null}catch{return null}}
function savedModeActive(){return appState()?.viewMode==='saved'}
function currentSave(){try{return typeof getCurrentSave==='function'?getCurrentSave():null}catch{return null}}
function diagnosticStore(){const s=appState();if(s){s.diagnostics=s.diagnostics||{};s.diagnostics.typeCandidates=s.diagnostics.typeCandidates||{recent:[],roles:{}};return s.diagnostics.typeCandidates}st._diagnostics=st._diagnostics||{recent:[],roles:{}};return st._diagnostics}
function saveSourceCounts(save=currentSave()){return {generals:(save?.generals||[]).length,generalStars:Object.keys(save?.generalStars||{}).length,generalSettings:Object.keys(save?.generalSettings||{}).length,inheritedSkills:Object.keys(save?.inheritedSkills||{}).length,equipments:(save?.equipments||[]).length,equipmentStars:Object.keys(save?.equipmentStars||{}).length,equipmentStages:Object.keys(save?.equipmentStages||{}).length,warhorses:Object.keys(save?.warhorses?.owned||{}).length}}
function flushCandidateDiagnostics(){const queue=st.diagnosticQueue.splice(0,12);st.diagnosticTimer=0;queue.forEach(({event,data})=>{try{if(typeof debugLog==='function')debugLog('typeCandidate:'+event,data)}catch{}try{if(window.HADO_TYPE_CANDIDATE_VERBOSE_LOGS&&savedModeActive()&&console&&console.info)console.info('[HADO type-candidate diagnostic]',data)}catch{}});if(st.diagnosticQueue.length)scheduleCandidateDiagnosticFlush()}
function scheduleCandidateDiagnosticFlush(){if(st.diagnosticTimer)return;const run=()=>flushCandidateDiagnostics();st.diagnosticTimer=1;if(typeof requestIdleCallback==='function')requestIdleCallback(run,{timeout:800});else setTimeout(run,0)}
function emitCandidateDiagnostic(event,payload){const data={timestamp:new Date().toISOString(),event,displayVersion:displayVersion(),typeId:st.sel?.typeId||'',typeName:type()?.typeName||'',purposeId:st.sel?.purposeId||'',purposeName:purpose()?.purposeName||'',savedMode:savedModeActive(),saveName:currentSave()?.name||'',saveSources:saveSourceCounts(),...payload};const store=diagnosticStore();store.latest=data;store.recent=Array.isArray(store.recent)?store.recent:[];store.recent.push(data);if(store.recent.length>80)store.recent.splice(0,store.recent.length-80);st.diagnosticQueue.push({event,data});if(st.diagnosticQueue.length>80)st.diagnosticQueue.splice(0,st.diagnosticQueue.length-80);scheduleCandidateDiagnosticFlush();return data}
function savedIndex(){const save=currentSave()||{};const generalNames=new Set(),equipmentNames=new Set();addSavedNames(generalNames,save.generals);addSavedNames(equipmentNames,save.equipments);return{generalNames,equipmentNames}}
function savedOwnershipRole(roleId){return ['main_general','vice_general','support_general','attendant','equipment','warhorse','warhorse_skill'].includes(roleId)}
function savedCandidateAllowed(v){if(!savedModeActive())return true;const idx=savedIndex(),name=canonicalName(v)||displayName(v);if(!savedMatchKey(name))return false;if(['main_general','vice_general','support_general','attendant'].includes(v.roleId))return savedNameSetHas(idx.generalNames,name);if(v.roleId==='equipment')return savedNameSetHas(idx.equipmentNames,name);if(v.roleId==='warhorse'||v.roleId==='warhorse_skill'){try{return Object.keys(getCurrentWarhorseData()?.owned||{}).length>0}catch{return false}}return true}
const ROMAN_SKILL_LEVELS=['Ⅰ','Ⅱ','Ⅲ','Ⅳ','Ⅴ','Ⅵ','Ⅶ','Ⅷ','Ⅸ','Ⅹ'];
const ASCII_ROMAN_SKILL_LEVELS=['I','II','III','IV','V','VI','VII','VIII','IX','X'];
const skillLevelNumber=v=>{const raw=String(v??'').trim().replace(/^Lv/i,'');let roman=ROMAN_SKILL_LEVELS.indexOf(raw);if(roman<0)roman=ASCII_ROMAN_SKILL_LEVELS.indexOf(saveName(raw));if(roman>=0)return roman+1;const n=Number(saveName(raw));return Number.isFinite(n)?Math.max(0,Math.min(10,Math.floor(n))):0};
function setOwnedSkill(out,levels,skillName,level){const n=savedMatchKey(skillName);if(!n)return;out.add(n);levels.set(n,Math.max(levels.get(n)||0,skillLevelNumber(level)||1))}
function addGrantedSkillNames(out,levels,skillName,level){try{if(typeof collectGrantedSkillEntriesForSavedIndex!=='function')return out;(collectGrantedSkillEntriesForSavedIndex(skillName,level)||[]).forEach(entry=>setOwnedSkill(out,levels,entry?.name,entry?.level||level||'Ⅰ'))}catch{}return out}
function savedSkillProfileForGeneral(name){if(!savedModeActive()||!['function','undefined'].includes(typeof findSavedGeneralItemByName))return null;try{const item=typeof findSavedGeneralItemByName==='function'?findSavedGeneralItemByName(name):null;if(!item)return {names:new Set(),levels:new Map()};const names=new Set(),levels=new Map(),map=typeof getResolvedGeneralSkillLevelMap==='function'?getResolvedGeneralSkillLevelMap(item):new Map();map.forEach((info,skillName)=>{const level=info?.level||info||'Ⅰ';setOwnedSkill(names,levels,skillName,level);addGrantedSkillNames(names,levels,skillName,level)});try{const inherited=typeof getCurrentInheritedSkill==='function'?getCurrentInheritedSkill(name):null;if(inherited?.skillName){setOwnedSkill(names,levels,inherited.skillName,'Ⅰ');addGrantedSkillNames(names,levels,inherited.skillName,'Ⅰ')}}catch{}return {names,levels}}catch{return null}}
function savedSkillNameSetForGeneral(name){const profile=savedSkillProfileForGeneral(name);return profile?profile.names:null}
function allMasterSkillNames(){const skills=appState()?.skills||[];if(st._skillNamesSource===skills&&Array.isArray(st._skillNames))return st._skillNames;st._skillNamesSource=skills;st._skillNames=skills.map(x=>savedMatchKey((typeof getItemDisplayName==='function'?getItemDisplayName(x):'')||x?.name||x?.title||'')).filter(Boolean).sort((a,b)=>b.length-a.length);return st._skillNames}
function savedRoleCompatibleText(row,roleId){try{if(window.HadoTypeScore&&typeof window.HadoTypeScore.roleCompatibleText==='function')return window.HadoTypeScore.roleCompatibleText(row,roleId)}catch{}return row?.matchedText||rowText(row)}
function rowText(row){return flat([row?.label,row?.statusEffectName,row?.featureId,row?.matchedText])}
const escRe=s=>String(s).replace(/[.*+?^${}()|[\]\\]/g,'\\$&');
const LEVEL_TOKEN='(?:10|[1-9]|Ⅹ|Ⅸ|Ⅷ|Ⅶ|Ⅵ|Ⅴ|Ⅳ|Ⅲ|Ⅱ|Ⅰ|VIII|VII|VI|IV|IX|III|II|I|X)';
const SEP='[」』）)\\s　]*';
const LEVEL_JOIN=SEP+'(?:の)?(?:技能)?'+SEP+'(?:を|が|は|なら|で|まで|に|へ)?'+SEP;
function requiredSkillLevel(text,skillName){const key=savedMatchKey(skillName);if(!text||!key)return 0;const source=savedMatchKey(text);const keyRe=new RegExp(escRe(key),'g');let required=0,m;while((m=keyRe.exec(source))){const tail=source.slice(m.index+key.length,m.index+key.length+28);const direct=tail.match(new RegExp('^'+SEP+'(?:Lv|lv)?('+LEVEL_TOKEN+')'));const viaLv=tail.match(new RegExp('^'+LEVEL_JOIN+'(?:Lv|lv|レベル)(?:が|は)?\\s*('+LEVEL_TOKEN+')'));const level=(viaLv&&viaLv[1])||(direct&&direct[1])||'Ⅰ';required=Math.max(required,skillLevelNumber(level)||1);if(keyRe.lastIndex===m.index)keyRe.lastIndex++}return required}
function rowSkillRejection(row,ownedSkills,roleId,ownedLevels=new Map()){if(!ownedSkills||row?.source!=='effect-text')return null;const scopedRaw=savedRoleCompatibleText(row,roleId);const text=savedMatchKey(scopedRaw);if(!text||text.includes('の戦法'))return null;const hits=allMasterSkillNames().filter(n=>n&&text.includes(n));for(const n of hits){const required=requiredSkillLevel(text,n)||1,owned=ownedLevels.get(n)||0;if(!ownedSkills.has(n))return {reason:'skill-unowned',skill:n,requiredLevel:required,ownedLevel:0,matchedText:String(scopedRaw||rowText(row)).slice(0,180)};if(required>owned)return {reason:'skill-level-insufficient',skill:n,requiredLevel:required,ownedLevel:owned,matchedText:String(scopedRaw||rowText(row)).slice(0,180)}}return null}
function rowUsesUnownedSkill(row,ownedSkills,roleId,ownedLevels=new Map()){return !!rowSkillRejection(row,ownedSkills,roleId,ownedLevels)}
function limitedRowText(row){return /限定|主将|副将|補佐|侍従/.test(String(row?.matchedText||rowText(row)||''))}
function auditSavedCandidateRows(v,profile){const typeRows=v?.typeFeatures||[],statusRows=v?.statusEffectRefs||[],rows=[...typeRows,...statusRows],audit={candidate:displayName(v),roleId:v?.roleId||'',ownedSkillCount:profile?.names?.size||0,sourceRows:rows.length,limitedRows:0,roleEmptyRows:0,skillRejectedRows:0,skillRejectedSamples:[],roleEmptySamples:[],keptTypeFeatures:[],keptStatusEffectRefs:[]};rows.forEach((row,idx)=>{if(limitedRowText(row))audit.limitedRows++;const scoped=savedRoleCompatibleText(row,v?.roleId);if(!String(scoped||'').trim()){audit.roleEmptyRows++;if(audit.roleEmptySamples.length<5)audit.roleEmptySamples.push({featureId:row?.featureId||'',label:row?.label||row?.statusEffectName||'',matchedText:String(row?.matchedText||rowText(row)).slice(0,180)});return}const rejection=rowSkillRejection(row,profile?.names,v?.roleId,profile?.levels);if(rejection){audit.skillRejectedRows++;if(audit.skillRejectedSamples.length<5)audit.skillRejectedSamples.push({featureId:row?.featureId||'',label:row?.label||row?.statusEffectName||'',...rejection});return}(idx<typeRows.length?audit.keptTypeFeatures:audit.keptStatusEffectRefs).push(row)});audit.keptRows=audit.keptTypeFeatures.length+audit.keptStatusEffectRefs.length;return audit}
function savedScoreEntity(v){if(!savedModeActive()||!['main_general','vice_general','support_general','attendant'].includes(v?.roleId))return v;const profile=savedSkillProfileForGeneral(canonicalName(v)||displayName(v));if(!profile)return {...v,_savedTypeCandidateAudit:{candidate:displayName(v),roleId:v?.roleId||'',profileMissing:true}};const audit=auditSavedCandidateRows(v,profile);return {...v,typeFeatures:audit.keptTypeFeatures,statusEffectRefs:audit.keptStatusEffectRefs,_savedOwnedSkillCount:profile.names.size,_savedTypeCandidateAudit:audit}}
function candidateVisibleByScore(v){return v._s.matchedCount>0}
function savedCandidateNote(){if(!savedModeActive())return '全データ表示: 全武将・全装備・全名馬などを候補対象にします。';const save=currentSave();return `保存データ表示: ${esc(save?.name||'保存データ')} のお気に入り武将・装備・名馬に候補を限定します。武将は保存将星で解放済みの技能だけを型評価へ反映し、適合する候補だけを選択可能として表示します。`}
function saveSignature(){const save=currentSave()||{};try{return JSON.stringify({mode:appState()?.viewMode||'',seq:appState()?.savedSearchCacheSeq||0,id:save.id||'',generals:save.generals||[],generalStars:save.generalStars||{},inheritedSkills:save.inheritedSkills||{},equipments:save.equipments||{},equipmentStages:save.equipmentStages||{},warhorses:save.warhorses?.owned||{}})}catch{return String(Date.now())}}
function roleRowsBaseCacheKey(role){return [displayVersion(),st.sel?.typeId||'',st.sel?.purposeId||'',role,saveSignature()].join('@@')}
function roleRowsCacheKey(role){return [roleRowsBaseCacheKey(role),norm(st.q)].join('@@')}
function clearRoleRowsCache(){st.roleCache.clear();st.roleBaseCache.clear()}
function recordRoleRowsDiagnostic(role,source,scored,owned,visible,finalRows){if(!savedModeActive())return;const rejectedByOwnership=scored.filter(v=>!savedCandidateAllowed(v)).slice(0,8).map(v=>displayName(v));const noScore=owned.filter(v=>!candidateVisibleByScore(v)).slice(0,8).map(v=>({name:displayName(v),matchedCount:v._s?.matchedCount||0,skillRejectedRows:v._savedTypeCandidateAudit?.skillRejectedRows||0,roleEmptyRows:v._savedTypeCandidateAudit?.roleEmptyRows||0,samples:v._savedTypeCandidateAudit?.skillRejectedSamples||[]}));const audits=owned.map(v=>v._savedTypeCandidateAudit).filter(Boolean);const summary={roleId:role,roleLabel:(ROLES.find(r=>r[0]===role)||[])[1]||role,sourceCount:source.length,ownedCount:owned.length,scoreVisibleCount:visible.length,finalCount:finalRows.length,ownershipRejectedCount:scored.length-owned.length,noScoreCount:owned.length-visible.length,limitedRows:audits.reduce((s,a)=>s+(a.limitedRows||0),0),roleEmptyRows:audits.reduce((s,a)=>s+(a.roleEmptyRows||0),0),skillRejectedRows:audits.reduce((s,a)=>s+(a.skillRejectedRows||0),0),rejectedByOwnership,noScoreSamples:noScore,skillRejectedSamples:audits.flatMap(a=>a.skillRejectedSamples||[]).slice(0,10),profileMissingCount:audits.filter(a=>a.profileMissing).length};const store=diagnosticStore();store.roles=store.roles||{};store.roles[role]=summary;emitCandidateDiagnostic('saved-role-rows',summary)}
function roleRowsBase(role){const key=roleRowsBaseCacheKey(role);if(st.roleBaseCache.has(key))return st.roleBaseCache.get(key);const started=performance.now(),source=st.data.roles.filter(v=>v.roleId===role),scored=source.map(scoreCandidate),owned=scored.filter(savedCandidateAllowed),visible=owned.filter(candidateVisibleByScore),sorted=visible.sort((a,b)=>b._s.confirmedScore-a._s.confirmedScore||b._s.conditionalMaxScore-a._s.conditionalMaxScore||Number(a.sourceIndex||0)-Number(b.sourceIndex||0));if(st.roleBaseCache.size>40)st.roleBaseCache.clear();st.roleBaseCache.set(key,{source,scored,owned,visible,sorted});recordRoleRowsDiagnostic(role,source,scored,owned,visible,sorted);emitCandidateDiagnostic('role-base-cache-miss',{roleId:role,sourceCount:source.length,visibleCount:visible.length,ms:Number((performance.now()-started).toFixed(1)),policy:'Update09 Phase2 separates scoring cache from search text filtering'});return st.roleBaseCache.get(key)}
function roleRows(role){const key=roleRowsCacheKey(role);if(st.roleCache.has(key))return st.roleCache.get(key);const q=norm(st.q),base=roleRowsBase(role),filtered=base.sorted.filter(v=>!q||norm(flat([v.displayName,v.name,v.typeFeatures,v.statusEffectRefs])).includes(q));if(st.roleCache.size>80)st.roleCache.clear();st.roleCache.set(key,filtered);return filtered}
function rows(){return roleRows(st.role)}
function rowKey(v){return `${v?.roleId||st.role}::${canonicalName(v)||displayName(v)}`}
function togglePick(key){const prev=st.picked;st.picked=st.picked===key?'':key;if(prev!==st.picked)render()}
function chipLabel(x){if(x==null)return '';if(typeof x==='string'||typeof x==='number')return String(x);if(Array.isArray(x))return x.map(chipLabel).filter(Boolean).join(' / ');if(typeof x==='object')return String(x.label||x.statusEffectName||x.displayName||x.name||x.featureId||'');return ''}
function chipLabels(v){return [...new Set([...(v.typeFeatures||[]),...(v.statusEffectRefs||[])].map(chipLabel).filter(Boolean))]}
function canonicalName(v){return String(v?.name||v?.displayName||'').trim()}
function displayName(v){return String(v?.displayName||v?.name||'').trim()}
function selectionReason(){const p=purpose();if(!p)return '';const rs=[...(p.primaryTypes||[]).map(v=>({...v,roleLabel:'主軸理由'})),...(p.secondaryTypes||[]).map(v=>({...v,roleLabel:'補助理由'}))];const row=rs.find(v=>v.typeId===st.sel?.typeId);return row?.reason?`${row.roleLabel}: ${row.reason}`:''}
function style(){if(document.getElementById('htc-style'))return;const e=document.createElement('style');e.id='htc-style';e.textContent=`#htc-open{position:fixed;right:18px;bottom:72px;z-index:99990;border:1px solid #1d4ed8;border-radius:999px;padding:11px 17px;background:#fff;color:#1d4ed8;font-weight:700;cursor:pointer}#htc-open:disabled{opacity:.5}#htc-overlay{position:fixed;inset:0;z-index:99992;background:#0f172a94;display:flex;align-items:center;justify-content:center;padding:16px}#htc-modal{width:min(1040px,100%);max-height:92dvh;background:#fff;border-radius:18px;display:grid;grid-template-rows:auto auto auto minmax(0,1fr);overflow:hidden;color:#172033}.htc-p{padding:14px 18px}.htc-head{display:flex;justify-content:space-between;gap:10px}.htc-actions{display:flex;gap:8px;flex-wrap:wrap}.htc-tabs{display:flex;gap:7px;flex-wrap:wrap;background:#f8fafc}.htc-btn,.htc-tab{border:1px solid #cbd5e1;background:#fff;border-radius:10px;padding:8px 11px;cursor:pointer}.htc-btn.primary{background:#1d4ed8;border-color:#1d4ed8;color:#fff}.htc-tab.on{border-color:#2563eb;background:#eff6ff;color:#1d4ed8;font-weight:700}.htc-search{width:100%;padding:10px;border:1px solid #cbd5e1;border-radius:10px}.htc-body{overflow:auto}.htc-list{display:grid;gap:8px}.htc-item{border:1px solid #d8e0eb;border-radius:12px;padding:11px;cursor:pointer;background:#fff;transition:background .15s,border-color .15s,box-shadow .15s}.htc-item:hover{border-color:#93c5fd;background:#f8fbff}.htc-item.on{border-color:#2563eb;background:#dbeafe;box-shadow:0 0 0 2px #bfdbfe inset}.htc-picked{display:inline-block;margin-left:8px;border-radius:999px;background:#1d4ed8;color:#fff;font-size:11px;padding:2px 7px;vertical-align:middle}.htc-title{font-weight:700}.htc-note,.htc-detail,.htc-score{font-size:12px;color:#64748b;line-height:1.55;margin-top:4px}.htc-score{font-weight:700;color:#334155}.htc-score strong{font-size:15px;color:#0f766e}.htc-chip{display:inline-block;border-radius:999px;padding:2px 7px;background:#eef2ff;color:#3730a3;margin:2px 4px 0 0}@media(max-width:720px){#htc-overlay{padding:0}#htc-modal{width:100%;height:100dvh;max-height:none;border-radius:0}}`;document.head.appendChild(e)}
function close(){document.getElementById('htc-overlay')?.remove()}
function createFromType(){if(typeof window.createFormationFromTypeSelection!=='function')return alert('新規部隊作成処理が読み込まれていません。');const f=window.createFormationFromTypeSelection({...st.sel,typeName:type()?.typeName||st.sel?.typeName||''});if(f)close()}
function render(){const m=document.getElementById('htc-modal'),rs=rows(),reason=selectionReason();m.innerHTML=`<div class="htc-p htc-head"><div><h2>型候補一覧</h2><div class="htc-note">${esc(displayVersion())} / 選択中の型: ${esc(type()?.typeName||'未選択')} / 目的: ${esc(purpose()?.purposeName||'指定なし')}</div>${reason?`<div class="htc-note">${esc(reason)}</div>`:''}<div class="htc-note">${savedCandidateNote()}</div><div class="htc-note">候補をクリックすると選択状態になります。同じ候補を再クリックすると選択解除します。</div></div><div class="htc-actions"><button class="htc-btn primary" data-create-formation>この型で新規部隊</button><button class="htc-btn" data-close>閉じる</button></div></div><div class="htc-p htc-tabs">${ROLES.map(([id,l])=>`<button class="htc-tab ${st.role===id?'on':''}" data-role="${id}">${l} (${roleRows(id).length})</button>`).join('')}</div><div class="htc-p"><input id="htc-q" class="htc-search" placeholder="名称・特徴で絞り込み" value="${esc(st.q)}"></div><div class="htc-p htc-body"><div class="htc-list">${rs.map(v=>{const k=rowKey(v),picked=st.picked===k;return `<div class="htc-item ${picked?'on':''}" role="button" tabindex="0" aria-pressed="${picked?'true':'false'}" data-pick-key="${esc(k)}" data-role-id="${esc(v.roleId||st.role)}" data-canonical-name="${esc(canonicalName(v))}" data-display-name="${esc(displayName(v))}"><div class="htc-title">${esc(displayName(v))}${picked?'<span class="htc-picked">選択中</span>':''}</div><div class="htc-score">適合スコア: <strong>${esc(window.HadoTypeScore.label(v._s))}</strong></div><div class="htc-detail">${esc(window.HadoTypeScore.summary(v._s))}</div><div class="htc-detail">${chipLabels(v).map(x=>`<span class="htc-chip">${esc(x)}</span>`).join('')}</div></div>`}).join('')||'<div class="htc-note">該当候補がありません。</div>'}</div></div>`;m.querySelectorAll('[data-close]').forEach(b=>b.onclick=close);m.querySelector('[data-create-formation]').onclick=createFromType;m.querySelectorAll('[data-role]').forEach(b=>b.onclick=()=>{st.role=b.dataset.role;st.q='';render()});m.querySelectorAll('[data-pick-key]').forEach(card=>{card.onclick=()=>togglePick(card.dataset.pickKey);card.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();togglePick(card.dataset.pickKey)}}});m.querySelector('#htc-q').oninput=e=>{st.q=e.target.value;render()}}
async function open(){st.sel=loadSel();if(!st.sel?.typeId)return alert('型編成ナビで型を選択し、「選択を保存」を押してください。');if(!st.data){const[a,b,c]=await Promise.all(FILES.map(fetchJson));st.data={roles:items(a,['items']),types:items(b,['items','types']),purposes:items(c,['items','purposes'])}}if(!type())throw Error(`選択中の型が見つかりません: ${st.sel.typeId}`);close();const o=document.createElement('div');o.id='htc-overlay';o.innerHTML='<section id="htc-modal"></section>';o.onclick=e=>{if(e.target===o)close()};document.body.appendChild(o);render()}
function isFormationTab(){const stt=appState();return stt?stt.mainTab==='formation':document.getElementById('formationScreen')&&!document.getElementById('formationScreen').classList.contains('tab-content-hidden')}
function syncVisibility(){const b=document.getElementById('htc-open');const visible=!!isFormationTab();if(b)b.hidden=!visible;if(!visible)close()}
function refresh(){clearRoleRowsCache();const b=document.getElementById('htc-open');if(b)b.disabled=!loadSel()?.typeId;syncVisibility()}
function getTypeCandidateDiagnostics(){return diagnosticStore()}
function exposeDebugApi(){window.HadoTypeCandidatesDebug={savedScoreEntity,rowUsesUnownedSkill,rowSkillRejection,auditSavedCandidateRows,savedSkillNameSetForGeneral,savedSkillProfileForGeneral,savedRoleCompatibleText,addGrantedSkillNames,requiredSkillLevel,skillLevelNumber,getDiagnostics:getTypeCandidateDiagnostics,emitCandidateDiagnostic,clearRoleRowsCache}}
function mount(){exposeDebugApi();style();const b=document.createElement('button');b.id='htc-open';b.textContent='型候補一覧';b.onclick=()=>open().catch(e=>alert(`型候補一覧の読込に失敗しました。\n${e.message}`));document.body.appendChild(b);refresh();addEventListener(EV,refresh);addEventListener('storage',refresh);new MutationObserver(syncVisibility).observe(document.documentElement,{attributes:true,subtree:true,attributeFilter:['class']});setInterval(syncVisibility,400)}
if(document.readyState==='loading')addEventListener('DOMContentLoaded',mount);else mount();
})();
